version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - myapp-postgres:/var/lib/postgresql/data:rw
  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - myapp-redis:/var/lib/redis/data:rw
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .myapp.env
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    env_file:
      - .myapp.env
volumes: 
  myapp-postgres:
  myapp-redis: